### ISSUE TITLE
Tracking for Epsilon rewrite

### ISSUE THREAD

**Issue by DarkGuy10** [DarkGuy10/BotClient#56]
This issue will track immediate changes for the Epsilon rewrite.

Major changes in this rewrite:
- [ ] Migrate backend to `discord.js v14`
- [ ] Migrate from `CRA` to `Next.js`
- [ ] Implement routing for easier page handling on frontend
- [ ] Add `Redux` for better data flow and state management
- [ ] Fix `TooltipManager` and `ContextMenuManager` api into wrapper-like components

**Comment by DarkGuy10** [comment]
`9cd2bb8a069b928df873ef05838985ceab97c500` finishes task 1

**Comment by DarkGuy10** [comment]
🚧 [Prepsilon](https://github.com/DarkGuy10/Prepsilon)

Skeleton repo for the next rewrite. 
This is still work in progress, but any criticism/advice is more than welcome ✨ 
Oh btw, we're switching the codebase to Typescript + Sass 🍷
